#!/usr/bin/env bash

RESULT=$(ssh -o LogLevel=DEBUG "${1}" "exit"  2>&1 | awk '/kex: algorithm:/{print $4}'| tr -d '\000-\037')

case "${RESULT}" in
  mlkem768x25519-sha256)
    echo "Excellent! Found ${RESULT}, this is the most secure!"
  ;;
  sntrup761x25519-sha512)
    echo "Good enough! Found ${RESULT}, which is good enough for now. Consider upgrading when possible!"
  ;;
  *)
    echo "Warning! Found ${RESULT}, upgrade ASAP!"
  ;;
esac
