#!/bin/bash

pushd /tmp/
    git clone https://github.com/vapoursynth/vapoursynth.git
    pushd vapoursynth
        ./autogen.sh
        ./configure --prefix=/home/ferenc/vapoursynth
        make
        make install
    popd
    git clone https://github.com/dubhater/vapoursynth-mvtools
    pushd vapoursynth-mvtools
        ./autogen.sh
        ./configure --prefix=/home/ferenc/vapoursynth/
        make
        make install
    popd
popd
