#!/bin/bash

OPENWRT_DIR=/tmp/openwrt
SDK=OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2
SDK_TAR=${SDK}.tar.bz2
SDK_MD5=${SDK_TAR}.md5
PLATFORM_URL=http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic

exitOnFail()
{
    echo -e "\n\t\t $1 \n"
    exit -1
}

checkSdkDependency()
{
    type -f make   2>&1 >/dev/null || exitOnFail "Install make first!"
    type -f patch  2>&1 >/dev/null || exitOnFail "Install patch!"
    type -f wget   2>&1 >/dev/null || exitOnFail "Install wget!"
    type -f ccache 2>&1 >/dev/null || exitOnFail "Install ccache or disable CONFIG_CCACHE in .config"
}

getSDK()
{
    wget ${PLATFORM_URL}/${SDK_TAR}
    curl -sL ${PLATFORM_URL}/md5sums | grep ${SDK_TAR} > ${SDK_MD5}
    md5sum -c ${SDK_MD5} || exitOnFail "MD5 failed!!!" 
    tar -xf ${SDK_TAR}
}

main()
{
    checkSdkDependency
    mkdir -p ${OPENWRT_DIR}
    pushd ${OPENWRT_DIR}

        # Obtain SDK
        getSDK

        pushd ${SDK}

            # Obtain package Definitions 
            ./scripts/feeds update packages
            ./scripts/feeds install -p packages nano

            make package/nano/compile

            # Make package index
            make package/index

            ls -lah bin/ar71xx/packages/packages/

        popd
    popd
}

main
