#!/bin/bash

SYSLINUX_DIR=/tmp/syslinux
SYSLINUX_URL_BASE=https://www.kernel.org/pub/linux/utils/boot/syslinux/6.xx/
SYSLINUX_FILE=syslinux-6.02.tar.xz
SYSLINUX_TAR=${SYSLINUX_FILE%.xz}
SYSLINUX_SRC=${SYSLINUX_TAR%.tar}

mkdir -p $SYSLINUX_DIR
pushd $SYSLINUX_DIR

if [[ $? != 0 ]]
then
    exit -1
fi


# Get syslinux:
wget ${SYSLINUX_URL_BASE}/${SYSLINUX_FILE}
unxz ${SYSLINUX_FILE}
tar -xf ${SYSLINUX_TAR}
pushd ${SYSLINUX_SRC} 

# See:
# http://www.syslinux.org/wiki/index.php/Doc/building
#
make bios installer
