#!/bin/bash

compileVMwareDirect()
{
    local readonly targetDirectory=/lib/modules/`uname -r`/misc
    [[ ! -d "${targetDirectory}" ]] && mkdir -p ${targetDirectory}

    cd /usr/lib/vmware/modules/source
    tar -xf vmnet.tar
    cd vmnet-only
    make clean
    make
    cd ..
    tar -xf vmmon.tar
    cd vmmon-only
    make clean
    make

    # Normally the ko files can also be fetched from here:
    # cp vmmon-only/vmmon.ko vmnet-only/vmnet.ko ${targetDirectory}/
    cp ../vmmon.o ${targetDirectory}/vmmon.ko
    cp ../vmnet.o ${targetDirectory}/vmnet.ko
    depmod -a
    /etc/init.d/vmware restart
}

compileVMware()
{
    vmware-modconfig --console --install-all
}

compileVirtualBox()
{
    # As of 6.0.0 vboxdrv doesn't seem to be present anymore
    # /etc/init.d/vboxdrv setup
    # Use vboxconfig insstead:
    /sbin/vboxconfig
    
}


[[ ! "$1" =~ ^vmware|vmware-direct|virtualbox|all$ ]] &&
{   
    echo -e "Usage:\n ${0##*/} <vmware|vmware-direct|virtualbox|all>" 
    exit -1
}

[[ "vmware" == "$1" ]] && compileVMware
[[ "vmware-direct" == "$1" ]] && compileVMwareDirect
[[ "virtualbox" == "$1" ]] && compileVirtualBox
[[ "all" == "$1" ]] && compileVirtualBox && compileVMware
