#!/bin/bash

NEOVIM_DIR=/tmp/neovim


checkReturnCode()
{
    if [[ $? != 0 ]]
    then
        echo "$1"
        exit -1
    fi
}


mkdir -p ${NEOVIM_DIR}
checkReturnCode "Failed to create directory"
pushd ${NEOVIM_DIR}
checkReturnCode "Failed to change directory"

# Clone
git clone git://github.com/neovim/neovim.git

# Compile
pushd ${NEOVIM_DIR}/neovim
make
checkReturnCode "Compilation Failed"

# Run
build/bin/nvim
checkReturnCode "Neovim exited unexpectedly"
