#!/bin/bash

NEOVIM_DIR=/tmp/neovim
LIB_DIR=~/neovim/usr/lib64/
INSTALL_DIR=~/neovim/


checkReturnCode()
{
    if [[ $? != 0 ]]
    then
        echo "$1"
        exit -1
    fi
}


pushd /tmp
checkReturnCode "Failed to change directory"

# Clone
git clone git://github.com/neovim/neovim.git

# Compile
pushd ${NEOVIM_DIR}
make -j 8 VERBOSE=1 CMAKE_BUILD_TYPE=Release CMAKE_EXTRA_FLAGS=-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}
checkReturnCode "Compilation Failed"
make install
checkReturnCode "Installation Failed"

[[ ! -d "${LIB_DIR}" ]] && mkdir -p ${LIB_DIR}
cp ${NEOVIM_DIR}/.deps/usr/lib64/libjemalloc.so* ${LIB_DIR}/
export  LD_LIBRARY_PATH=${LIB_DIR}:$LD_LIBRARY_PATH

# Run
#build/bin/nvim
${INSTALL_DIR}/bin/nvim
checkReturnCode "Neovim exited unexpectedly"
