#!/bin/bash

compileVMwareDirect()
{
    local version=$(vmware --version | awk '{printf "%d", $3}')
    local readonly targetDirectory=/lib/modules/`uname -r`/misc
    [[ ! -d "${targetDirectory}" ]] && mkdir -p ${targetDirectory}

    cd /usr/lib/vmware/modules/source
    tar -xf vmnet.tar
    cd vmnet-only
    make
    cd ..
    tar -xf vmmon.tar
    cd vmmon-only
    make
    if [[ 12 > ${version} ]] 
    then
        cp ../vmmon.o ${targetDirectory}/vmmon.ko
        cp ../vmnet.o ${targetDirectory}/vmnet.ko
    else
        cd ..
        cp vmmon-only/vmmon.ko vmnet-only/vmnet.ko ${targetDirectory}/
    fi
    depmod -a
    /etc/init.d/vmware restart
}

compileVMware()
{
    vmware-modconfig --console --install-all
}

compileVirtualBox()
{
    /etc/init.d/vboxdrv setup
}


[[ ! "$1" =~ ^vmware|vmware-direct|virtualbox|all$ ]] &&
{   
    echo -e "Usage:\n ${0##*/} <vmware|vmware-direct|virtualbox|all>" 
    exit -1
}

[[ "vmware" == "$1" ]] && compileVMware
[[ "vmware-direct" == "$1" ]] && compileVMwareDirect
[[ "virtualbox" == "$1" ]] && compileVirtualBox
[[ "all" == "$1" ]] && compileVirtualBox && compileVMware
