#!/bin/bash

OPENWRT_DIR=/tmp/openwrt

type -f ccache 2>&1 >/dev/null
if [[ $? != 0 ]]
then
    echo "Install ccache first!!!"
    exit -1
fi

mkdir -p $OPENWRT_DIR
pushd $OPENWRT_DIR

if [[ $? != 0 ]]
then
    exit -1
fi

# Obtain SDK
wget http://downloads.openwrt.org/barrier_breaker/14.07/ar71xx/generic/OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
tar -xf OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2.tar.bz2
pushd OpenWrt-SDK-ar71xx-for-linux-x86_64-gcc-4.8-linaro_uClibc-0.9.33.2

if [[ $? != 0 ]]
then
    exit -1
fi

    # Obtain package Definitions 
    git clone git@github.com:openwrt/packages.git
    ./scripts/feeds update packages
    ./scripts/feeds install -p packages nano

    make package/nano/compile

    # Make package index
    make package/index

    ls -lah bin/ar71xx/packages/packages/

popd
