#!/usr/bin/env bash

# Download the latest Citrix Receiver 13.3 for Linux (SuSe full package x86_64)
# https://www.citrix.com/downloads/citrix-receiver/linux/receiver-for-linux-latest.html
# 

# If you get SSL Error 61 from Citrix then
# do the certificate linking as described here: 
# http://ubuntuforums.org/showthread.php?t=1975705
# ln -s /usr/share/ca-certificates/mozilla/* /opt/Citrix/ICAClient/keystore/cacerts

firefox http://dwp.ra.ericsson.net/
