#!/usr/bin/env bash
lspci -mmv |
  jc --lspci |
  jq --raw-output '.[] | select(.class == "VGA compatible controller") | .vendor' |
  while read -r vendor; do
    case "${vendor}" in
    'Intel Corporation')
      echo
      echo 'Intel supported HW Codecs:'
      echo
      # sudo dnf install libva-utils
      vainfo 2>&1 | awk '/Supported profile and entrypoints/{found=1; next} found{print substr($1,10,length($1))}'
      ;;
    'NVIDIA Corporation')
      echo
      echo 'NVIDIA supported HW Codecs:'
      echo
      # github.com/philipl/nv-video-info
      nvdecinfo | awk 'NR >4 && /[^-]/{print $1}' | sort | uniq
      ;;
    *)
      echo "Unkown vendor: ${vendor}"
      exit 1
      ;;
    esac
  done

# sudo dnf install vulkan-tools
echo
echo 'Vulkan supported HW Codecs:'
echo
vulkaninfo 2>&1 | awk '/VK_KHR_video_decode_[^q]/{print substr($1,21,length($1))}'
