#!/usr/bin/env bash

NODE1='<fillme>'
NODE2='<fillme>'
NODE3='<fillme>'

# Ensure supported distro:
#https://www.suse.com/suse-rke2/support-matrix/all-supported-versions/rke2-v1-34/

# https://docs.rke2.io/install/configuration
# The RKE2 config file needs to be created manually. You can do that by running touch /etc/rancher/rke2/config.yaml as a privileged user
# https://docs.rke2.io/install/ha#2-launch-the-first-server-node
#
# Exposing etcd-metrics with `listen-metrics-url`
# https://github.com/rancher/rke2/discussions/4024
#
# Scheduler metrics by default are only available on 127.0.0.1 (normally vanilla kubernetes would do 0.0.0.0),
# but this is a security hardening on RKE2.
# By default on RKE2 this works:
# /var/lib/rancher/rke2/bin/kubectl get --kubeconfig /etc/rancher/rke2/rke2.yaml --server https://127.0.0.1:10259 --raw /metrics | less
# Exposing them for cluster internal traffic, with `kube-scheduler-arg`
# https://docs.rke2.io/reference/server_config#flags
# In particular with `bind-address`
# https://kubernetes.io/docs/reference/command-line-tools-reference/kube-scheduler/#options
#
# And this is still not enough because the certificate is invalid for anything else than 127.0.0.1:
# `Unable to connect to the server: tls: failed to verify certificate: x509: certificate is valid for 127.0.0.1, ::1, not 9.30.138.200`
# So you have to do:
# /var/lib/rancher/rke2/bin/kubectl get --kubeconfig /etc/rancher/rke2/rke2.yaml --insecure-skip-tls-verify  --server https://9.30.138.200:10259 --raw /metrics | less
# Or from inside of the curl container that has the Service Account:
# curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)"   https://9.30.138.200:10259/metrics | less -R
#
# The `controller-manager`  & `apiserver` also need the same args similarly.
# Test the API server with:
# curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https://kubernetes.default.svc:443/metrics  | less -R
# Test the controller-manager with:
# curl -k -H "Authorization: Bearer $(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" https:///9.30.138.200:10259/metrics | less -R
ssh "root@${NODE1}" 'mkdir -p /etc/rancher/rke2/ && touch /etc/rancher/rke2/config.yaml'
ssh "root@${NODE1}" 'cat >/etc/rancher/rke2/config.yaml' <<EOF
token: my-shared-secret
tls-san:
  - $NODE1
etcd-arg:
  - "listen-metrics-urls=http://0.0.0.0:2381"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
kube-apiserver-arg:
  - "bind-address=0.0.0.0"
EOF

ssh "root@${NODE1}" 'curl -sfL https://get.rke2.io | sh -'
ssh "root@${NODE1}" 'systemctl enable rke2-server.service && systemctl start rke2-server.service'

for n in ${NODE2} ${NODE3}; do
  # https://docs.rke2.io/install/ha#3-launch-additional-server-nodes
  ssh "root@${n}" 'mkdir -p /etc/rancher/rke2/ && touch /etc/rancher/rke2/config.yaml'
  ssh "root@${n}" 'cat >/etc/rancher/rke2/config.yaml' <<EOF
server: https://$NODE1:9345
token: my-shared-secret
tls-san:
  - $n
etcd-arg:
  - "listen-metrics-urls=http://0.0.0.0:2381"
kube-scheduler-arg:
  - "bind-address=0.0.0.0"
kube-controller-manager-arg:
  - "bind-address=0.0.0.0"
kube-apiserver-arg:
  - "bind-address=0.0.0.0"
EOF
  ssh "root@${n}" 'curl -sfL https://get.rke2.io | sh -'
  ssh "root@${n}" 'systemctl enable rke2-server.service && systemctl start rke2-server.service'
done

# https://docs.rke2.io/install/ha#4-confirm-cluster-is-functional
# Watch until all 3 is Ready
ssh "root@${NODE1}" /var/lib/rancher/rke2/bin/kubectl get nodes --kubeconfig /etc/rancher/rke2/rke2.yaml --watch
