#!/bin/bash
export SWT_GTK3=1
export GTK_THEME=Adwaita:dark
#export GTK2_RC_FILES=/usr/share/themes/Adwaita/gtk-3.0/gtkrc
#export GTK3_RC_FILES=/usr/share/themes/Adwaita/gtk-3.0
/mnt/backup/Devel/Scala/IDE_4/eclipse/eclipse
