#!/bin/bash

parseOptions()
{
    while getopts ":v" opt "${args}";
    do
        case $opt in
            v)
                echo "Video has been triggered! (-v)" >&2
                VIDEO="1"
                args=${args[1]}
                ;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                exit -1
                ;;
        esac
    done
}

displayContent()
{
    set "${args}"
    local regex='^http(s)?://9gag.com/gag/([^?]*)([?]sc=.*)?$'
    local base_url='http://d24w6bsrhbeh9d.cloudfront.net/photo'
    if [[ $1 =~ $regex ]];
    then
        local ID="${BASH_REMATCH[2]}"
        if [[ ! -z ${VIDEO} ]]
        then
            mpv "${base_url}/${ID}_460svwm.webm"
        else
            wget -qO- "${base_url}/${ID}_700b.jpg" | display -
        fi
    else
        echo "error can't match $1"
    fi
}

main()
{
    parseOptions
    displayContent
}

args=($@)
main
