#!/bin/bash

parseOptions()
{
    while getopts ":v" opt "${args}";
    do
        case $opt in
            v)
                echo "Video has been triggered! (-v)" >&2
                VIDEO="1"
                args=${args[1]}
                ;;
            \?)
                echo "Invalid option: -$OPTARG" >&2
                exit -1
                ;;
        esac
    done
}

displayContent()
{
    set "${args}"
    local regex='^http://9gag.com/gag/([^?]*)([?]sc=.*)?$'
    if [[ $1 =~ $regex ]];
    then
        local ID="${BASH_REMATCH[1]}"
        if [[ ! -z ${VIDEO} ]]
        then
            mpv "http://img-9gag-fun.9cache.com/photo/${ID}_460svwm.webm"
        else
            display "http://img-9gag-fun.9cache.com/photo/${ID}_700b.jpg"
        fi
    else
        echo "error can't match $1"
    fi
}

main()
{
    parseOptions
    displayContent
}

args=($@)
main
