#!/bin/bash
notify-send --urgency=normal "Updating adblock"


EASYLIST_PATH="${HOME}/.config/wyebadblock/"

if [[ ! -d "${EASYLIST_PATH}" ]];
then
    mkdir -p "${EASYLIST_PATH}"
fi

pushd /tmp
    wget -O 1.txt https://easylist-downloads.adblockplus.org/easylist.txt
    wget -O 2.txt https://raw.githubusercontent.com/zpacman/Blockzilla/master/Blockzilla.txt
    wget -O 3.txt https://easylist-downloads.adblockplus.org/fanboy-annoyance.txt
    cat 1.txt 2.txt 3.txt > "${EASYLIST_PATH}/easylist.txt"
    result="$?"
popd

if [[ "${result}" == "0" ]];
then
    notify-send --urgency=normal "Adblock update done"
else
    notify-send --urgency=critical "Failed to update adblock"
fi
