#!/usr/bin/env bash

# For password don't use the normal AMT password
# there is a secondary FB password for the KVM session

# Download tvnjviewer from:
# https://www.tightvnc.com/download/2.8.3/tvnjviewer-2.8.3-bin-gnugpl.zip
if [ ! -f ./tightvnc-jviewer.jar ];
then
    wget -q 'https://www.tightvnc.com/download/2.8.3/tvnjviewer-2.8.3-bin-gnugpl.zip'
    unzip -j "tvnjviewer-2.8.3-bin-gnugpl.zip" "nossh/tightvnc-jviewer.jar" -d ./
    rm tvnjviewer-2.8.3-bin-gnugpl.zip
fi

java -jar ./tightvnc-jviewer.jar \
                -vvv \
                -host=192.168.1.171 \
                -port=5900 \
                -password=$(<~/.private/AMT_FB_PASSWORD.vnc) \
                -sshHost=$(<~/.private/AMT_FB_SSH_HOST.vnc) \
                -sshUser=$(<~/.private/AMT_FB_SSH_USER.vnc) \
                -sshPort=22 \
                -showConnectionDialog=No
